# Generated by Django 3.2.16 on 2022-10-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('AD', 'Admin'), ('RE', 'Recipe Maker'), ('EM', 'Employee')], default='EM', max_length=2),
        ),
    ]
