# Generated by Django 3.2.16 on 2022-12-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('AD', 'Admin'), ('LI', 'Lab Incharge'), ('SI', 'Shift Incharge'), ('WK', 'Worker')], default='WK', max_length=2),
        ),
    ]
