# Generated by Django 3.2.16 on 2022-12-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
