# Generated by Django 3.2.16 on 2022-12-14 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredient', '0010_alter_ingredientnotes_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('physical_location', models.IntegerField(unique=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='ingredient.ingredient')),
            ],
            options={
                'db_table': 'container',
            },
        ),
    ]
