# Generated by Django 3.2.16 on 2022-12-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
