# Generated by Django 3.2.16 on 2022-12-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0002_alter_container_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='remarks',
        ),
    ]
