# Generated by Django 3.2.16 on 2022-11-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsinventory',
            name='added_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
