# Generated by Django 3.2.16 on 2022-11-10 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_alter_ingredientsinventory_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsinventory',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_added_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
