# Generated by Django 3.2.16 on 2022-12-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0002_auto_20221115_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='order_volume',
            field=models.IntegerField(),
        ),
    ]
