# Generated by Django 3.2.16 on 2022-11-02 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('threshold_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredient_code', models.CharField(max_length=128, unique=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingredient',
            },
        ),
        migrations.CreateModel(
            name='IngredientApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=128, unique=True)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'ingredient_app',
            },
        ),
        migrations.CreateModel(
            name='IngredientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=128, unique=True)),
                ('recipe_order', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'ingredient_type',
            },
        ),
        migrations.CreateModel(
            name='IngredientNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=50, unique=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ingredient.ingredient')),
            ],
            options={
                'db_table': 'ingredient_notes',
            },
        ),
        migrations.CreateModel(
            name='IngredientIncompatible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incompatible', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredient_incompatible_incompatible', to='ingredient.ingredient')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredient_incompatible_ingredient', to='ingredient.ingredient')),
            ],
            options={
                'db_table': 'ingredient_incompatibile',
            },
        ),
        migrations.CreateModel(
            name='IngredientApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ingredient.ingredient')),
                ('ingredient_application', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ingredient.ingredientapp')),
            ],
            options={
                'db_table': 'ingredient_applications',
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ingredient.ingredienttype'),
        ),
    ]
