# Generated by Django 3.2.16 on 2022-12-13 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientnotes',
            unique_together={('ingredient', 'notes')},
        ),
        migrations.AlterModelTable(
            name='ingredientnotes',
            table=None,
        ),
    ]
