# Generated by Django 3.2.16 on 2022-12-13 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_auto_20221213_0503'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredientnotes',
            table='ingredient_notes',
        ),
    ]
