# Generated by Django 3.2.16 on 2022-12-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0003_alter_ingredientnotes_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientnotes',
            name='notes',
            field=models.CharField(max_length=50),
        ),
    ]
