# Generated by Django 3.2.16 on 2022-12-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0004_alter_ingredientnotes_notes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredientnotes',
            table=None,
        ),
    ]
