# Generated by Django 3.2.16 on 2022-12-13 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0005_alter_ingredientnotes_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredientnotes',
            table='ingredient_notes',
        ),
    ]
