# Generated by Django 3.2.16 on 2022-12-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0007_alter_ingredientnotes_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientnotes',
            unique_together={('ingredient', 'notes')},
        ),
    ]
