# Generated by Django 3.2.16 on 2022-12-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0008_alter_ingredientnotes_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientnotes',
            name='notes',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientnotes',
            unique_together=set(),
        ),
    ]
