# Generated by Django 3.2.16 on 2022-12-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0010_alter_ingredientnotes_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingredientapplications',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingredientincompatible',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingredientnotes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
